#ifndef PK2_PARTICLES
#define PK2_PARTICLES

enum { //Particles
	PARTIKKELI_EI_MIKAAN,
	PARTIKKELI_TAHTI,
	PARTIKKELI_HOYHEN,
	PARTIKKELI_POLYPILVI,
	PARTIKKELI_VALO,
	PARTIKKELI_KIPINA,
	PARTIKKELI_PISTE,
	PARTIKKELI_SAVUPILVI,
	PARTIKKELI_TAHTI2
};
enum { //BG particles
	TAUSTAPARTIKKELI_VESIPISARA,
	TAUSTAPARTIKKELI_LEHTI1,
	TAUSTAPARTIKKELI_LEHTI2,
	TAUSTAPARTIKKELI_LEHTI3,
	TAUSTAPARTIKKELI_LEHTI4,
	TAUSTAPARTIKKELI_HIUTALE1,
	TAUSTAPARTIKKELI_HIUTALE2,
	TAUSTAPARTIKKELI_HIUTALE3,
	TAUSTAPARTIKKELI_HIUTALE4
};

PK_Partikkelit_Tyhjenna();
PK_Partikkelit();

PK_Taustapartikkelit_Tyhjenna();
PK_Taustapartikkelit();

PK_Partikkelit_Piirra();
PK_Partikkeli_Uusi();

#endif
